20210222 EF AND CORE DotNet Core 5 MVC Application Test/Controllers/InputAndExceptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test.Contexts;
using _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test.Models;

namespace _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test.Controllers
{
    public class InputAndExceptionsController : Controller
    {
        private readonly CTHCPRDContext _context;

        public InputAndExceptionsController(CTHCPRDContext context)
        {
            _context = context;
        }

        // GET: InputAndExceptions
        public async Task<IActionResult> Index()
        {
            return View(await _context.InputAndExceptions.ToListAsync());
        }

        // GET: InputAndExceptions/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inputAndException = await _context.InputAndExceptions
                .FirstOrDefaultAsync(m => m.Emplid == id);
            if (inputAndException == null)
            {
                return NotFound();
            }

            return View(inputAndException);
        }

        // GET: InputAndExceptions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: InputAndExceptions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Emplid,Name,EarnCode,Descr,YrMth,Earnings,Hours")] InputAndException inputAndException)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inputAndException);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(inputAndException);
        }

        // GET: InputAndExceptions/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inputAndException = await _context.InputAndExceptions.FindAsync(id);
            if (inputAndException == null)
            {
                return NotFound();
            }
            return View(inputAndException);
        }

        // POST: InputAndExceptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Emplid,Name,EarnCode,Descr,YrMth,Earnings,Hours")] InputAndException inputAndException)
        {
            if (id != inputAndException.Emplid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inputAndException);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InputAndExceptionExists(inputAndException.Emplid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(inputAndException);
        }

        // GET: InputAndExceptions/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inputAndException = await _context.InputAndExceptions
                .FirstOrDefaultAsync(m => m.Emplid == id);
            if (inputAndException == null)
            {
                return NotFound();
            }

            return View(inputAndException);
        }

        // POST: InputAndExceptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var inputAndException = await _context.InputAndExceptions.FindAsync(id);
            _context.InputAndExceptions.Remove(inputAndException);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InputAndExceptionExists(string id)
        {
            return _context.InputAndExceptions.Any(e => e.Emplid == id);
        }
    }
}

20210222 EF AND CORE DotNet Core 5 MVC Application Test/Controllers/SalaryDatumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test.Contexts;
using _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test.Models;

namespace _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test.Controllers
{
    //[BindProperties(SupportsGet = true)]
    public class SalaryDatumsController : Controller
    {
        private readonly CTHCPRDContext _context;

        public SalaryDatumsController(CTHCPRDContext context)
        {
            _context = context;
        }

        
        //[HttpPost("{employee_id}")]
        //[HttpPost("{effective_date}")]
        // GET: SalaryDatums
        //[AcceptVerbs("POST")]
        public async Task<IActionResult> Index(string emplid, string effective_Date)
        {


           // var salaryDatum = "";
            
            var salaryDatum = _context.SalaryData.Where(e => e.Emplid == emplid)
                .Where(e => Convert.ToInt32(e.EffectiveDate) <= Convert.ToInt32(effective_Date))
                .OrderBy(e => e.EFFDT)
                .AsNoTracking();
            


            /*
            if (salaryDatum == null)
            {
                return NotFound();
            }
            */

            return View(await salaryDatum.ToListAsync());
            //return View(salaryDatum);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Test(string emplid, string effectiveDate)
        {


            // var salaryDatum = "";

            var salaryDatum = _context.SalaryData.Where(e => e.Emplid == emplid)
                .Where(e => Convert.ToInt32(e.EffectiveDate) <= Convert.ToInt32(effectiveDate))
                .OrderBy(e => e.EFFDT)
                .AsNoTracking();



            /*
            if (salaryDatum == null)
            {
                return NotFound();
            }
            */

            return View(await salaryDatum.ToListAsync());
            //return View(salaryDatum);


        }

        // GET: SalaryDatums/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salaryDatum = await _context.SalaryData
                .FirstOrDefaultAsync(m => m.Emplid == id);
            if (salaryDatum == null)
            {
                return NotFound();
            }

            return View(salaryDatum);
        }

        // GET: SalaryDatums/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SalaryDatums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Emplid,Year,Month,TotalSsp,YearTotal,GenSsp,FireSsp,PoliceSsp")] SalaryDatum salaryDatum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(salaryDatum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(salaryDatum);
        }

        // GET: SalaryDatums/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salaryDatum = await _context.SalaryData.FindAsync(id);
            if (salaryDatum == null)
            {
                return NotFound();
            }
            return View(salaryDatum);
        }

        // POST: SalaryDatums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Emplid,Year,Month,TotalSsp,YearTotal,GenSsp,FireSsp,PoliceSsp")] SalaryDatum salaryDatum)
        {
            if (id != salaryDatum.Emplid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salaryDatum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaryDatumExists(salaryDatum.Emplid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(salaryDatum);
        }

        // GET: SalaryDatums/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salaryDatum = await _context.SalaryData
                .FirstOrDefaultAsync(m => m.Emplid == id);
            if (salaryDatum == null)
            {
                return NotFound();
            }

            return View(salaryDatum);
        }

        // POST: SalaryDatums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var salaryDatum = await _context.SalaryData.FindAsync(id);
            _context.SalaryData.Remove(salaryDatum);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalaryDatumExists(string id)
        {
            return _context.SalaryData.Any(e => e.Emplid == id);
        }
    }
}

20210222 EF AND CORE DotNet Core 5 MVC Application Test/Views/Shared/_Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

20210222 EF AND CORE DotNet Core 5 MVC Application Test/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetSalaries">Get Salary Information</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalaryDatums" asp-action="Index">Salary Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InputAndExceptions" asp-action="Index">Input and Exceptions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - _20210222_EF_AND_CORE_DotNet_Core_5_MVC_Application_Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>